### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [frosit/zsh-plugin-homeassistant-cli#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by frosit** [comment]
Hi @unixorn, Glad to hear you want to add it your list. I'm sorry for the delayed response but I only just noticed your issue. I did a little refactoring and updated the docs together with your license request. I'll leave the PR to you.

I've been running the dev branch myself past months, mostly stable except for some cross platform issues. I'll finish that soon and pay more attention to maintaining this repo. Feel free if you have any suggestions or feedback :)
